blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'

urlpatterns = [
    path('', views.all_blogs,name='all_blogs'),
    path('<int:blog_id>', views.detail,name='detail'),


]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('blog/', include('blog.urls')) ,

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title=models.CharField(max_length=200)
    date=models.DateField()
    description=models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=300)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Blog

# Create your views here.

def all_blogs(request):
    blog= Blog.objects.order_by('-date')
    return render(request,'blog/all_blogs.html',{'blogs':blog})

def detail(request,blog_id):
    blog= get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'blog/start.html' %}
{% block content %}


<nav style="padding: 25px; font-weight: bold; font-size: 20px; color:white; background-color:#0082ef; font-size: 100%;">Blogs</nav>

<h2 style="margin-top: 10px;margin-left: 10px ; ;">Tasnia has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2 style="margin-left: 10px ;">{{ blog.title }}</h2></a>
<h4 style="margin-left: 10px ;">{{ blog.date|date:'M d Y' }}</h4>
<h5 style="margin-left: 10px ;">{{ blog.description|striptags|truncatechars:100 }}</h5>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/start.html' %}
{% block content %}



<h1>{{ blog.title }}</h1>
<br>
{{ blog.date|date:'F jS Y' }}
<br><br>
{{ blog.description|safe }}

{% endblock %}

blog/templates/blog/start.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Tasnia's Blog</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/start.html' %}
{% block content %}
{% load static %}

<nav>
    <input type="checkbox" id="check">
    <label for="check" class="checkbtn">
      <i class="fas fa-bars"></i>
    </label>
    <label class="logo">Tasnia's portfolio</label>
    <ul>
        <li><a class="active" href="{% static '/portfolio/TAS.pdf' %}">Resume</a></li>
        <li><a href="{% url 'blog:all_blogs' %}">Blog</a></li>
        <li><a href="https://www.linkedin.com/in/tasnia-sharmin-3b1788198/">LinkedIn</a></li>
        <li><a href="https://github.com/tasnia18">GitHub</a></li>
    </ul>
</nav>

<p style="margin-top: 10px; margin-right: 30px; font-size: large;">Hey, this is my homepage, so I have to say something about myself. 
    </p>
<img src="{% static '/portfolio/m.jpg' %}" style="height:400px; width :300px;float: right;margin-right:30px;">
<p style="font-size: large;">Sometimes it is hard to introduce yourself because you know yourself so well that 
    you do not know where to start with. Let me give a try to see what kind of image you have about 
    me through my self-description. I hope that my impression about myself and your impression about me are
     not so different. Here it goes..<br>I am a person who is positive about every aspect of life. There are many things I like to do, 
    to see, and to experience. I like to think, I like to dream; I like to talk, I like to listen. I like to see the sunrise in the morning, I like to see the moonlight at night; I like to feel 
    the music flowing on my face, I like to smell the wind coming from the ocean. I like to look at the clouds in the 
    sky with a blank mind, I like to do thought experiment when I cannot sleep in the middle of the night. I like flowers
     in spring, rain in summer, leaves in autumn, and fog in winter.I like to be surrounded by people. 
     I like delicious food and comfortable shoes; And, I like to laugh.</p>


<br clear="all">
<h1 style="margin-bottom: 20px;font-weight: bold;">My project{{ projects.count|pluralize }}</h1>
{% for project in projects %}

{% if project.url %}
<a href="{{ project.url }}"><img src="{{ project.image.url }}" style="height:100px; width:100px;">
{% endif %}  
<h4>{{ project.title }}</h4></a>
<h5>{{ project.description }}</h5> 
{% endfor %}

{% endblock %}

portfolio/templates/portfolio/start.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  list-style: none;
  text-decoration: none;
}
nav{
  background: #0082e6;
  height: 80px;
  width: 100%;
}
label.logo{
  color: #f2f2f2;
  font-size: 33px;
  line-height: 80px;
  padding: 0 10px;
  font-weight: 600;
  font-family: 'Poppins', sans-serif;
}
nav ul{
  float: right;
  margin-right: 60px;
}
nav ul li{
  display: inline-block;
  line-height: 80px;
  margin: 0 2px;
}
nav ul li a{
  color: #f2f2f2;
  font-weight: 500;
  font-size: 20px;
  padding: 7px 13px;
  border-radius: 3px;
  /* text-transform: uppercase; */
  font-family: 'Poppins', sans-serif;
}
a.active,a:hover{
  background: #1b9bff;
  transition: .5s;
}
.checkbtn{
  font-size: 30px;
  color: white;
  float: right;
  line-height: 80px;
  margin-right: 40px;
  cursor: pointer;
  display: none;
}
#check{
  display: none;
}
@media (max-width: 952px){
  label.logo{
    font-size: 27px;
    padding-left: 25px;
  }
  nav ul li a{
    font-size: 16px;
  }
}
@media (max-width: 858px){
  .checkbtn{
    display: block;
    margin-right: 40px;
  }
  ul{
    position: fixed;
    width: 100%;
    height: 100vh;
    background: #2c3e50;
    top: 80px;
    left: -100%;
    text-align: center;
    transition: all .5s;
  }
  nav ul li{
    display: block;
    margin: 50px 0;
    line-height: 30px;
  }
  nav ul li a{
    font-size: 20px;
  }
  a:hover,a.active{
    background: none;
    color: #0082e6;
  }
  #check:checked ~ ul{
    left: 0;
  }
}
section{
  background: url(bg1.jpg) no-repeat;
  background-size: cover;
  height: calc(100vh - 80px);
}

    </style>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static '/portfolio/logo.png' %}" >
    <title>Tasnia Sharmin</title>
  </head>
  <body style="margin:30px;">

    

  
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>